#!/usr/bin/env bash
# Install Ngnix to web server wb01

sudo apt-get update -y
sudo apt-get install nginx -y

# Configuring Ngnix to listen to port 80
# sudo ufw allow 'Nginx HTTP'
# Creating a simple html page with "Hello, world!" message
# sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'

# redirect
# sudo sed -i '/server_name _;/c server_name _;\n\trewrite ^\/redirect_me https:\/\/youtube.com permanent;' /etc/nginx/sites-enabled/default


echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i 's/server_name _;/server_name _;\n\trewrite \/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;\n\terror_page 404 \/404.html;\n\tlocation \/404.html{\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}/' /etc/nginx/sites-enabled/default

# Custom HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# tset configurations
sudo nginx -t

# Restart nginx
sudo service nginx restart

