#!/usr/bin/env bash
#Block incoming traffics except port 80/22/443

sudo apt-get update
sudo apt-get install ufw -y
sudo ufw status verbose
sudo ufw deny incoming
sudo ufw allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
echo "y" | sudo ufw enable
sudo yfw status verbose