#!/usr/bin/env bash
# This script sets docker container with apache
# Update package lists
sudo apt-get update

# Install Apache
sudo apt install apache2

# Start Apache service
sudo service apache2 start

# Create the HTML file
echo "Hello Holberton" > /var/www/html/index.html
